name: flutter_stetho_example
description: Demonstrates how to use the flutter_stetho plugin.
environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_stetho:
    path: ../

flutter:
  uses-material-design: true
